// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// count_if
double count_if(arma::uvec x);
RcppExport SEXP POMaSPU_count_if(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::uvec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(count_if(x));
    return rcpp_result_gen;
END_RCPP
}
// rankC
arma::vec rankC(NumericVector x);
RcppExport SEXP POMaSPU_rankC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(rankC(x));
    return rcpp_result_gen;
END_RCPP
}
// permhigh
List permhigh(arma::mat Ts, arma::mat rsum, arma::mat X, arma::mat po, int nperm);
RcppExport SEXP POMaSPU_permhigh(SEXP TsSEXP, SEXP rsumSEXP, SEXP XSEXP, SEXP poSEXP, SEXP npermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Ts(TsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rsum(rsumSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type po(poSEXP);
    Rcpp::traits::input_parameter< int >::type nperm(npermSEXP);
    rcpp_result_gen = Rcpp::wrap(permhigh(Ts, rsum, X, po, nperm));
    return rcpp_result_gen;
END_RCPP
}
